### ISSUE TITLE
ccMessage.ControlValue empty

### ISSUE THREAD

**Issue by imorrish** [Psychlist1972/Windows-10-PowerShell-MIDI#1]
Not getting a value back for ccMessage.ControlValue on the ControlChangeMessageReceived event
Channel and Controller values are ok.

**Comment by Psychlist1972** [comment]
Can you tell me a bit more about what you're using? I'm getting values back here from my launchpad. I've added Control Change to the input event example, and also added some more debug information to the DLL to make this easier to test out.

![image](https://cloud.githubusercontent.com/assets/1421146/9361729/d0dbe968-466a-11e5-8bf7-318fec565133.png)

**Comment by imorrish** [comment]
Typo on my part. I was using $event.sourceEventArgs.controlvalue
I'm using Behringer CMD PL-1 http://www.behringer.com/EN/Products/CMD-PL-1.aspx
to control BMD Hyperdeck https://www.blackmagicdesign.com/products/hyperdeckstudio

Will post project soon.
Thanks so much for providing this DLL, I'm not a developer and was trying to use some old Midi library from XP days using com in PowerShell:-(

**Comment by Psychlist1972** [comment]
Excellent, thanks. I'll close this then.

I checked out the project under your GH account. Looks like it'll be cool!
